package model;

/**
 * The values which can be pulled from the controller.
 *
 */
public enum FieldTypes {
TEAMID, SPEED, AVGWEIGHT, ORGANIC,
SLAUGTHERAMOUNTNIGHT, SLAUGTHERAMOUNTDAY,
STOPNIGHT, STOPDAY,
DAYEXPECTED, TOTALEXPECTED,
TOTALSLAUGTHERAMOUNT, EXPECTEDFINISH,
PRODUCTIONSTOPS, DAILYMESSAGES, EXPECTEDPERHOUR

}
