package model;

/**
 * The values which can be pulled from the controller.
 *
 */
public enum FieldTypes {
SPEED, AVGWEIGTH, ORGANIC,
SLAUGTHERAMOUNTNIGHT, SLAUGTHERAMOUNTDAY,
STOPNIGHT, STOPDAY,
DAYEXSPECTED, TOTALEXPECTED,
TOTALSLAUGTHERAMOUNT, EXPECTEDFINISH,
PRODUCTIONSTOPS, DAILYMESSAGES

}
